[build]
  command = "npm run build" # Or whatever your build command is
  functions = "functions"
  publish = "public" # Set this to your build output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Connection = "upgrade"
    Upgrade = "websocket"

[build.environment]
  NODE_VERSION = "22"
